# Generated by Django 5.2.6 on 2025-10-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detetime_created',
            new_name='datetime_created',
        ),
    ]
